use_frameworks!

target 'RxRequester_Example' do
  pod 'RxRequester', :path => '../'

  pod 'RxSwift',    '~> 4.0'
  pod 'SwiftMessages', '6.0.1'
  pod 'Moya/RxSwift', '~> 13.0.0'

  target 'RxRequester_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
