use_frameworks!

target 'RxRequester_Example' do
  pod 'RxRequester', :path => '../'

  target 'RxRequester_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
